### ISSUE TITLE
Ошибка с STM32

### ISSUE THREAD

**Issue by P55-rgb** [AlexGyver/GyverString#6]
![image](https://github.com/AlexGyver/GyverString/assets/63473590/c964049a-0048-4634-b5ad-49be6a8b4566)
![image](https://github.com/AlexGyver/GyverString/assets/63473590/ba9831c8-ea1b-464c-88a9-6ee0d7e241ca)
![image](https://github.com/AlexGyver/GyverString/assets/63473590/68763684-c440-44ac-ac13-50dfbed69602)
![image](https://github.com/AlexGyver/GyverString/assets/63473590/28de5d23-1261-40cd-b357-2a605ba85632)

Сделал всё по инструкции, но выдаёт вот эту ошибку.
Этого файла SoftwareSerial.h нет на диске С !
Как это вылечить?

**Comment by GyverLibs** [comment]
Писать разработчику ядра, почему у него нет стандартной библиотеки

**Comment by P55-rgb** [comment]
У вас есть контакты разработчика?
Как он тестировал прошивку не понятно :(

**Comment by P55-rgb** [comment]
Какая версия прошивки для AVR Меги последняя от Гайвера и где её можно скачать?

**Comment by GyverLibs** [comment]
> У вас есть контакты разработчика?

нет, откуда. Где брали ядро, там и ищите

> Как он тестировал прошивку не понятно :(

разработчик ядра и разработчик gyverstring - разные люди. Прошивка тестировалась только на AVR, работа на всех существующих платформах нигде не заявлена и не обязана быть

> версия прошивки для AVR Меги последняя

ну очевидно та у которой самая старшая цифра версии, она в папке одна такая

**Comment by P55-rgb** [comment]
> > У вас есть контакты разработчика?
> 
> нет, откуда. Где брали ядро, там и ищите
> 
> > Как он тестировал прошивку не понятно :(
> 
> разработчик ядра и разработчик gyverstring - разные люди. Прошивка тестировалась только на AVR, работа на всех существующих платформах нигде не заявлена и не обязана быть
> 
> > версия прошивки для AVR Меги последняя
> 
> ну очевидно та у которой самая старшая цифра версии, она в папке одна такая

![image](https://github.com/AlexGyver/GyverString/assets/63473590/4251f640-434a-40bc-ae53-8357bfae2ae5)
Описание этого лежит на сайте Гайвера или на деревне у дедушки?
Я делаю по инструкции не работает.
Если проблема в ядре, то зачем давать на него ссылки?
![image](https://github.com/AlexGyver/GyverString/assets/63473590/b99e7ef3-c83c-4343-9394-ec3b73a8c00e)
И очевидно не работает последняя версия GyverMatrixOS_v1.12 !
GyverMatrixOS_v1.12 - эта ваша программа или надо искать разработчика?
GyverMatrixOS_v1.12 на Меге запускается, но не работает связь по блютуз со смарфоном, на STM32 вообще не собирается. 
На Нано собираю связь работает, на Меге нет связи!
Можете помочь с Мегой и STM32?

**Comment by P55-rgb** [comment]
Ещё можно к Нане прикрутить микро SD.
Кто-нибудь это делал?

**Comment by GyverLibs** [comment]
Если на сайте указано - значит тестировалось и работает. Если не работает - что то поменялось в версиях библиотек или ядер

**Comment by P55-rgb** [comment]
> Если на сайте указано - значит тестировалось и работает. Если не работает - что то поменялось в версиях библиотек или ядер

Вы можете помочь решить эту проблему?

**Comment by GyverLibs** [comment]
С stm32 - нет, это в любом случае костыли и не стоит её использовать в этом проекте. На меге должно работать, у людей работает
